///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsImagesProfileImage = 'assets/images/profileImage.svg';
  static const String fontsCairoBold = 'assets/fonts/Cairo-Bold.ttf';
  static const String fontsCairoMedium = 'assets/fonts/Cairo-Medium.ttf';
  static const String fontsCairoRegular = 'assets/fonts/Cairo-Regular.ttf';
  static const String fontsCairoSemiBold = 'assets/fonts/Cairo-SemiBold.ttf';
  static const String iconIcon = 'assets/icon/icon.png';
  static const String imagesAppIcon = 'assets/images/app_icon.png';
  static const String imagesAppleIcon = 'assets/images/apple_icon.svg';
  static const String imagesArrowSwap = 'assets/images/arrow-swap.svg';
  static const String imagesFacebookIcon = 'assets/images/facebook_icon.svg';
  static const String imagesFeaturedItemBackground = 'assets/images/featured_item_background.svg';
  static const String imagesFilterIcon = 'assets/images/filter_icon.svg';
  static const String imagesFruitsTest = 'assets/images/fruits_test.png';
  static const String imagesGoogleIcon = 'assets/images/google_icon.svg';
  static const String imagesHomeFilled = 'assets/images/home_filled.svg';
  static const String imagesHomeOutlined = 'assets/images/home_outlined.svg';
  static const String imagesLocationIcon = 'assets/images/location_icon.svg';
  static const String imagesLogo = 'assets/images/logo.svg';
  static const String imagesMinusIcon = 'assets/images/minus_icon.svg';
  static const String imagesNotification = 'assets/images/notification.svg';
  static const String imagesPageViewItem1BackgroundImage = 'assets/images/page_view_item1_background_image.svg';
  static const String imagesPageViewItem1Image = 'assets/images/page_view_item1_image.svg';
  static const String imagesPageViewItem2BackgroundImage = 'assets/images/page_view_item2_background_image.svg';
  static const String imagesPageViewItem2Image = 'assets/images/page_view_item2_image.svg';
  static const String imagesPenIcon = 'assets/images/pen_icon.svg';
  static const String imagesPlant = 'assets/images/plant.svg';
  static const String imagesPlusIcon = 'assets/images/plus_icon.svg';
  static const String imagesProductsFilled = 'assets/images/products_filled.svg';
  static const String imagesProductsOutlined = 'assets/images/products_outlined.svg';
  static const String imagesProfileImage = 'assets/images/profileImage.png';
  static const String imagesSearchIcon = 'assets/images/search_icon.svg';
  static const String imagesShoppingCartFilled = 'assets/images/shopping-cart_filled.svg';
  static const String imagesShoppingCartOutlined = 'assets/images/shopping-cart_outlined.svg';
  static const String imagesSplashBottom = 'assets/images/splashBottom.svg';
  static const String imagesTrashIcon = 'assets/images/trash_icon.svg';
  static const String imagesUserFilled = 'assets/images/user_filled.svg';
  static const String imagesUserOutlined = 'assets/images/user_outlined.svg';
  static const String imagesWatermelon = 'assets/images/watermelon.png';

}
