// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdUng934Jzc5aNEfZBVk12ttIIBKyPwVM',
    appId: '1:969590178999:web:e821c058c9e48bfb973932',
    messagingSenderId: '969590178999',
    projectId: 'fruit-hub-fad11',
    authDomain: 'fruit-hub-fad11.firebaseapp.com',
    storageBucket: 'fruit-hub-fad11.firebasestorage.app',
    measurementId: 'G-HLR2P4R6HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOWDrMWTemaEFFtRyl-T59WmDANNfztWk',
    appId: '1:969590178999:android:0d044dad3e30a225973932',
    messagingSenderId: '969590178999',
    projectId: 'fruit-hub-fad11',
    storageBucket: 'fruit-hub-fad11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkdLF25jsBxe4D0LwEMiSuVnjXjrtHpuo',
    appId: '1:969590178999:ios:3b1df14caa0e9118973932',
    messagingSenderId: '969590178999',
    projectId: 'fruit-hub-fad11',
    storageBucket: 'fruit-hub-fad11.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkdLF25jsBxe4D0LwEMiSuVnjXjrtHpuo',
    appId: '1:969590178999:ios:3b1df14caa0e9118973932',
    messagingSenderId: '969590178999',
    projectId: 'fruit-hub-fad11',
    storageBucket: 'fruit-hub-fad11.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdUng934Jzc5aNEfZBVk12ttIIBKyPwVM',
    appId: '1:969590178999:web:ad2303c5b3c8ce47973932',
    messagingSenderId: '969590178999',
    projectId: 'fruit-hub-fad11',
    authDomain: 'fruit-hub-fad11.firebaseapp.com',
    storageBucket: 'fruit-hub-fad11.firebasestorage.app',
    measurementId: 'G-2KZR50HV6M',
  );
}
